{
 "title": "RxJava",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Function   f(x) = 3 * sin( (PI /4) * val ) - 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "application:function_gauge" }
   ]
  },
  {
   "title": "Up Time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application:uptime_gauge_seconds"
    }
   ]
  },
  {
   "title": "Rotor (rpm)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "application:rotor_gauge_rpm" }
   ]
  },
  {
   "title": "Pear Inc. (price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "application:pear_gauge_price" }
   ]
  },
  {
   "title": "MajorCurrent (price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:major_current_gauge_price"
    }
   ]
  },
  {
   "title": "Macrohard (price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:macrohard_gauge_price"
    }
   ]
  }
 ]
}