# # config file version
apiVersion: 1

providers:
- name: 'Prometheus'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  editable: true
  updateIntervalSeconds: 30
  options:
    path: ..\conf\provisioning\